# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 915eff1944efe45cb9962ed6c092cbd68541e10fd7fe8af24fd2b86d990d43c27782b39d4695ffae6e9428deeb2816b9a9dde22f61287a95b82b6002e36c0b32

test:
  secret_key_base: a47b8959e10c23fa22e2d5a08b035196e5cc2e887463165802bd35f8023ccee73993539edfb173bfb9a9d489fb9d077808453e3cfebbe2d8423f2c05becc82fb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
